title: My Elegant Jekyll Site
description: A simple and elegant Jekyll template
author: Your Name
url: "https://example.com"
baseurl: ""
theme: minima
markdown: kramdown

# Social Media Links
social_links:
  - name: Twitter
    url: https://twitter.com/yourusername
  - name: GitHub
    url: https://github.com/yourusername
